GFN(
  (t_model): TimeEncodingPIS(
    (t_model): Sequential(
      (0): Linear(in_features=128, out_features=64, bias=True)
      (1): GELU(approximate='none')
      (2): Linear(in_features=64, out_features=64, bias=True)
    )
  )
  (s_model): StateEncodingPIS(
    (x_model): Linear(in_features=66, out_features=64, bias=True)
  )
  (joint_model): JointPolicyPIS(
    (model): Sequential(
      (0): GELU(approximate='none')
      (1): Sequential(
        (0): Linear(in_features=64, out_features=64, bias=True)
        (1): GELU(approximate='none')
      )
      (2): Sequential(
        (0): Linear(in_features=64, out_features=64, bias=True)
        (1): GELU(approximate='none')
      )
      (3): Linear(in_features=64, out_features=132, bias=True)
    )
  )
  (langevin_scaling_model): LangevinScalingModelPIS(
    (lgv_model): Sequential(
      (0): Linear(in_features=128, out_features=64, bias=True)
      (1): Sequential(
        (0): GELU(approximate='none')
        (1): Linear(in_features=64, out_features=64, bias=True)
      )
      (2): Sequential(
        (0): GELU(approximate='none')
        (1): Linear(in_features=64, out_features=64, bias=True)
      )
      (3): GELU(approximate='none')
      (4): Linear(in_features=64, out_features=1, bias=True)
    )
  )
)

  0%|                                                                                                                    | 1/25001 [00:25<178:05:51, 25.65s/it]
Traceback (most recent call last):
  File "/home/radoslavralev/Documents/Thesis/gfn-diffusion/energy_sampling/buffer.py", line 149, in sample
    sample, reward = next(self.data_iter)
AttributeError: 'ReplayBuffer' object has no attribute 'data_iter'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "train.py", line 346, in <module>
    train()
  File "train.py", line 313, in train
    metrics['train/loss'] = train_step(energy, gfn_model, gfn_optimizer, i, args.exploratory,
  File "train.py", line 236, in train_step
    loss = bwd_train_step(energy, gfn_model, buffer, buffer_ls, exploration_std, it=it)
  File "train.py", line 268, in bwd_train_step
    samples, rewards = buffer_ls.sample()
  File "/home/radoslavralev/Documents/Thesis/gfn-diffusion/energy_sampling/buffer.py", line 151, in sample
    self.data_iter = iter(self.loader)
AttributeError: 'ReplayBuffer' object has no attribute 'loader'